import { PlaceHolderImages } from '@/lib/placeholder-images';

const getImage = (id: string) => PlaceHolderImages.find(img => img.id === id)?.imageUrl || '';
const getImageHint = (id: string) => PlaceHolderImages.find(img => img.id === id)?.imageHint || '';

export const userData = {
  name: 'Sophie Elizabeth',
  avatarUrl: getImage('user-avatar'),
  avatarHint: getImageHint('user-avatar'),
};

export const metricsData = {
  balance: 165000,
  followers: 2000000,
  likes: 1000000,
  videoCount: 15,
};

export const videosData = [
  {
    id: 1,
    title: 'Nasty sophie',
    thumbnailUrl: getImage('video-thumb-1'),
    thumbnailHint: getImageHint('video-thumb-1'),
    views: 257000,
    likes: 12000,
    comments: 1200,
    publishedAt: '3 days ago',
    category: 'Gaming',
    videoUrl: '/VID-20251022-WA0030.mp4'
  },
  {
    id: 2,
    title: 'Sophie in the bathtub',
    thumbnailUrl: getImage('video-thumb-2'),
    thumbnailHint: getImageHint('video-thumb-2'),
    views: 89000,
    likes: 7500,
    comments: 800,
    publishedAt: '1 week ago',
    category: 'Vlog',
    videoUrl: '/VID-20251022-WA0035.mp4'
  },
  {
    id: 3,
    title: 'Sophie fine body',
    thumbnailUrl: getImage('video-thumb-3'),
    thumbnailHint: getImageHint('video-thumb-3'),
    views: 175000,
    likes: 9800,
    comments: 1500,
    publishedAt: '2 weeks ago',
    category: 'Travel',
    videoUrl: '/VID-20251022-WA0031.mp4'
  },
  {
    id: 4,
    title: 'Sophie in the mood',
    thumbnailUrl: getImage('video-thumb-4'),
    thumbnailHint: getImageHint('video-thumb-4'),
    views: 320000,
    likes: 21000,
    comments: 2000,
    publishedAt: '1 month ago',
    category: 'Cooking',
    videoUrl: '/VID-20251022-WA0032.mp4'
  },
   {
    id: 5,
    title: 'Sophie is riding it hard',
    thumbnailUrl: getImage('video-thumb-5'),
    thumbnailHint: getImageHint('video-thumb-5'),
    views: 112000,
    likes: 8200,
    comments: 950,
    publishedAt: '1 month ago',
    category: 'Tech',
    videoUrl: '/VID-20251022-WA0033.mp4'
  },
  {
    id: 7,
    title: 'Sophie is bored today',
    thumbnailUrl: getImage('video-thumb-7'),
    thumbnailHint: getImageHint('video-thumb-7'),
    views: 98000,
    likes: 6100,
    comments: 750,
    publishedAt: '2 months ago',
    category: 'Vlog',
  },
  {
    id: 8,
    title: 'Sophie black on black',
    thumbnailUrl: '/IMG-20251022-WA0026.jpg',
    thumbnailHint: 'newly added image',
    views: 1000,
    likes: 100,
    comments: 10,
    publishedAt: '1 day ago',
    category: 'Photography',
  },
  {
    id: 9,
    title: 'Sophie black panties',
    thumbnailUrl: '/girl-1.jpg',
    thumbnailHint: 'girl with headphones',
    views: 2000,
    likes: 200,
    comments: 20,
    publishedAt: '2 days ago',
    category: 'Photography',
  },
  {
    id: 10,
    title: 'Naked Sophie',
    thumbnailUrl: '/girl-2.jpg',
    thumbnailHint: 'girl with headphones',
    views: 3000,
    likes: 300,
    comments: 30,
    publishedAt: '3 days ago',
    category: 'Photography',
  },
  {
    id: 11,
    title: 'The photo is pinky',
    thumbnailUrl: '/IMG-20251022-WA0024.jpg',
    thumbnailHint: 'tech setup',
    views: 4000,
    likes: 400,
    comments: 40,
    publishedAt: '4 days ago',
    category: 'Photography',
  },
  {
    id: 12,
    title: 'Sophie is using the shower',
    thumbnailUrl: '/IMG-20251022-WA0027.jpg',
    thumbnailHint: 'cooking inspiration',
    views: 5000,
    likes: 500,
    comments: 50,
    publishedAt: '5 days ago',
    category: 'Photography',
  },
  {
    id: 13,
    title: 'Sophie on orange',
    thumbnailUrl: '/IMG-20251022-WA0028.jpg',
    thumbnailHint: 'travel photography',
    views: 6000,
    likes: 600,
    comments: 60,
    publishedAt: '6 days ago',
    category: 'Photography',
  },
];
